services:
  db:
    container_name: delivero_db
    image: postgres
    environment:
      POSTGRES_USER: ${DELIVERO_DB_USER}
      POSTGRES_PASSWORD: ${DELIVERO_DB_PASSWORD}
      POSTGRES_DB: ${DELIVERO_DB_NAME}
    ports:
      - "${DELIVERO_DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data